test = тестовое сообщение
successfully-connected = Подключение с базой данных установлено!
unsuccessfully-connected = Соединение с базой данных не установлено!
table-created = Таблица создана или уже существует!
table-not-created = Во время создания таблицы произошла ошибка!
successfully-read = Данные из таблицы успешно получены!
unsuccessfully-read = Во время получения данных из таблицы возникла ошибка!
successfully-write = Данные были успешно записаны в таблицу!
unsuccessfully-write = Во время записи данных в таблицу возникла ошибка!
successfully-update = Данные в таблице успешно обновлены!
unsuccessfully-update = Во время обновления данных в таблице возникла ошибка!
successfully-delete = Один контакт успешно удален из таблицы базы данных!
unsuccessfully-delete = Во время удаления контакта из таблицы базы данных возникла ошибка!